#!/bin/bash
set -e

# Install RStudio
wget https://download2.rstudio.org/server/jammy/amd64/rstudio-server-2022.07.2-576-amd64.deb
apt-get update && apt-get install -y gdebi-core
gdebi -n rstudio-server-2022.07.2-576-amd64.deb

# Remove unnecessary packages to save space
apt-get clean && rm -rf /var/lib/apt/lists/*

# Add RStudio to PATH
echo 'PATH="/usr/lib/rstudio-server/bin:$PATH"' >> ~/.bashrc
source ~/.bashrc
